#!/bin/bash

# Script to add OpenRouter API key to AWS Secrets Manager
# Usage: ./scripts/add-openrouter-key.sh YOUR_API_KEY

set -e

if [ $# -eq 0 ]; then
    echo "❌ Error: Please provide your OpenRouter API key"
    echo "Usage: ./scripts/add-openrouter-key.sh YOUR_API_KEY"
    echo ""
    echo "To get your OpenRouter API key:"
    echo "1. Go to https://openrouter.ai/"
    echo "2. Sign up or log in"
    echo "3. Go to Keys section"
    echo "4. Create a new API key"
    exit 1
fi

API_KEY="$1"
SECRET_ID="junokit-api-secrets"

echo "🔑 Adding OpenRouter API key to AWS Secrets Manager..."

# Update the secret with the new API key
aws secretsmanager update-secret \
    --secret-id "$SECRET_ID" \
    --secret-string "{\"openRouterApiKey\":\"$API_KEY\",\"slackBotToken\":\"\",\"githubToken\":\"\",\"googleClientId\":\"\",\"googleClientSecret\":\"\",\"autoGenerated\":\"PLACEHOLDER\"}" \
    --region eu-north-1

if [ $? -eq 0 ]; then
    echo "✅ OpenRouter API key successfully added to AWS Secrets Manager!"
    echo ""
    echo "🚀 Next steps:"
    echo "1. Deploy the updated Lambda function: cd infrastructure/aws-cdk && cdk deploy"
    echo "2. Test the chat functionality at: http://localhost:3002/chat"
    echo ""
    echo "🤖 Your AI chat is now ready with the DeepSeek R1 model!"
else
    echo "❌ Failed to update AWS Secrets Manager"
    echo "Make sure you have AWS CLI configured and proper permissions"
    exit 1
fi 